# path should be real path, relative path is not supported yet.
op_target_path: "./Acc/configs/op_target.yaml"
dump_root_path: "./dump_info"

white_list: "./Acc/configs/white_list.yaml"

# mode must be chosen from ["real_data", "random"]
dump_mode: "real_data"

# set cards number
global_rank: 1
target_step: [0]
