# path should be real path, relative path is not safe.

# Target APIs.
op_target_path: "None"
# If op_target_path is set to None, tool will set the default config in repository configs.
dump_root_path: "./dump_info"

# Remote Path
remote_path: "/root/paddlejob/workspace/PaddleAPEX_dump/"
Async_dump: False

# mode must be chosen from ["real_data", "random"]
dump_mode: "random"

# target_step is a list, dump api function will turn on at the specific step
target_step: [0]
